name: Opt-In Parser

on:
  issues:
    types: [opened, reopened]

jobs:
  generate-pull-request:
    if: startsWith(github.event.issue.title, 'OPT-IN:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

#       - name: Install Dependencies
#         run: |
#           cd scripts
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

      - name: Run Opt-In Parser
        run: |
          cd scripts
          ISSUE_LINK="${{github.event.issue.url}}" ISSUE_BODY="${{ github.event.issue.body }}" python opt_in_parser.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Opt-In ${{env.PROJECT_NAME}}"
          branch: opt-in-${{env.PROJECT_NAME}}
          title: "Opt-In ${{env.PROJECT_NAME}}"
          body: |
            This pull request updates the opt-in data collection list based on the latest opt-in issues.
            
            Project name: ${{env.PROJECT_NAME}}
            Issue link: ${{env.ISSUE_LINK}}
            
            Please review the changes and merge if appropriate.
